Project 3/Project/Controllers/DocumentPoaController.cs
using System.Data.SqlClient;
using Microsoft.AspNetCore.Mvc;
using Project.Models;
using Project.Services;

namespace Project.Controllers;

public class DocumentPoaController : Controller
{
    private readonly ICustomerService _customerService;
    private readonly IDocumentPoaService _documentPoaService;
    public List<DocumentPoaModel> AllDocumentPoa { get; set; } = new();
    private readonly string _connectionString;
    private bool _isInitialized;

    public DocumentPoaController(IConfiguration configuration, ICustomerService customerService,
        IDocumentPoaService documentPoaService)
    {
        _customerService = customerService;
        _documentPoaService = documentPoaService;
        _connectionString = configuration.GetConnectionString("DefaultConnection");
    }
    
    public IActionResult DocumentPoaForm(DocumentPoaModel documentPoaModel)
    {
        documentPoaModel.CreateDate = DateTime.Now;
        return View(documentPoaModel);
    }
    public IActionResult DocumentPoaAbuDhabiForm(DocumentPoaModel documentPoaModel)
    {
        return View(documentPoaModel);
    }

    [HttpPost]
    public IActionResult CreateDocumentPoa(DocumentPoaModel documentPoaModel)
    {
        var customer = new Customer
        {
            FullName = documentPoaModel.FullName,
            MotherName = documentPoaModel.MotherName,
            Address = documentPoaModel.Address,
            Email = documentPoaModel.Email,
            MobileNumber = documentPoaModel.MobileNumber,
            WhatsAppNumber = documentPoaModel.WhatsAppNumber,
            TRNNumber = ""
        };
        
        _customerService.Initialize();
        _customerService.CreateCustomer(customer);
        
        _documentPoaService.Initialize();
        using (SqlConnection connection = new SqlConnection(_connectionString))
        {
            connection.Open();

            string sql = "INSERT INTO documentPoa (OriginalLanguage, Subject, Note, Signature, CreateDate, AppointmentDate, CustomerId) " +
                         "VALUES (@OriginalLanguage, @Subject, @Note, @Signature, @CreateDate, @AppointmentDate, @CustomerId)";

            using (SqlCommand command = new SqlCommand(sql, connection))
            {
                command.Parameters.AddWithValue("@OriginalLanguage", documentPoaModel.OriginalLanguage);
                command.Parameters.AddWithValue("@Subject", documentPoaModel.Subject);
                command.Parameters.AddWithValue("@Note", documentPoaModel.Note);
                command.Parameters.AddWithValue("@Signature",
                    Convert.FromBase64String(documentPoaModel.SignatureString.Split(',')[1]));
                command.Parameters.AddWithValue("@CreateDate", documentPoaModel.CreateDate);
                command.Parameters.AddWithValue("@AppointmentDate", documentPoaModel.AppointmentDate);
                command.Parameters.AddWithValue("@CustomerId",
                    _customerService.AllCustomers.First(x => x.MobileNumber == customer.MobileNumber)
                        .CustomerId);

                command.ExecuteNonQuery();
            }
        }
        
        AllDocumentPoa.Add(documentPoaModel);
        return RedirectToAction("Index", "Home");
    }
    
    public IActionResult DocumentPoaTrackPage()
    {
        _documentPoaService.Initialize();
        return View(AllDocumentPoa.ToArray());
    }
    
    public IActionResult DocumentPoaShowPage(int id)
    {
        _documentPoaService.Initialize();
        var documentPoa = AllDocumentPoa.FirstOrDefault(c => c.DocumentPoaId == id);
        return View(documentPoa);
    }
    
    public IActionResult Delete(int proformaInvoiceId)
    {
        _documentPoaService.Initialize();
        using (SqlConnection connection = new SqlConnection(_connectionString))
        {
            connection.Open();

            string sql = "DELETE FROM documentPoa WHERE DocumentPoaId = @DocumentPoaId";

            using (SqlCommand command = new SqlCommand(sql, connection))
            {
                command.Parameters.AddWithValue("@DocumentPoaId", proformaInvoiceId);

                command.ExecuteNonQuery();
            }
        }
        var documentPoa = AllDocumentPoa.FirstOrDefault(c => c.DocumentPoaId == proformaInvoiceId);
        AllDocumentPoa.Remove(documentPoa);
        return RedirectToAction("DocumentPoaTrackPage");
    }
}

Project 3/Project/Views/DocumentPoa/DocumentPoaTrackPage.cshtml
@model Project.Models.DocumentPoaModel[]

@{
    ViewData["Title"] = "Document Poa Tracking";
}

<!DOCTYPE html>

<div id="top-bar">
    <div id="selectedpanelitem">
        <h3>
            Document Poa Tracking
        </h3>
    </div>
</div>

<br/><br/><br/>

<table class="styled-table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().CustomerId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MotherName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MobileNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().OriginalLanguage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Subject)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MotherName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MobileNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OriginalLanguage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subject)
            </td>

            <td>
                <a class="tablebutton" href="@Url.Action("DocumentPoaShowPage", "DocumentPoa", new { id = item.DocumentPoaId })">
                    <span class="tablebutton_text">Show</span>
                </a>
                <a class="tablebutton" href="@Url.Action("Delete", "DocumentPoa", new { id = item.DocumentPoaId })" onclick="return confirmDelete()">
                    <span class="tablebutton_text">Delete</span>
                </a>
            </td>
        </tr>
    }
    </tbody>
</table>

@section scripts {
    <script>
        $(document).ready(function () {
            // Iterate over each canvas with the 'displayCanvas' class
            $('.displayCanvas').each(function () {
                var canvas = this;
                var signaturePad = new SignaturePad(canvas);

                // Function to load and display the signature
                function loadAndDisplaySignature(signatureData) {
                    signaturePad.fromDataURL(signatureData);
                }

                // Call the function with the signature data from the canvas's data attribute
                console.log("display:" + $(canvas).data('signaturestring'));
                loadAndDisplaySignature($(canvas).data('signaturestring'));
            });
        });
        
        function confirmDelete() {
                return confirm("Are you sure you want to delete this item?");
        }
    </script>
}