Project 3/Project/Controllers/ProformaInvoiceController.cs
using System.Data.SqlClient;
using System.Diagnostics;
using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using Project.Models;
using Project.Services;

namespace Project.Controllers;

public class ProformaInvoiceController : Controller
{
    private readonly ICustomerService _customerService;
    private readonly IProformaInvoiceService _proformaInvoiceService;
    private readonly ISettingsService _settingsService;
    
    private readonly IDocumentAttestationService _documentAttestationService;
    private readonly IDocumentCommitmentLetterService _documentCommitmentLetterService;
    private readonly IDocumentConsentLetterService _documentConsentLetterService;
    private readonly IDocumentInvitationService _documentInvitationService;
    private readonly IDocumentPoaService _documentPoaService;
    private readonly IDocumentSircularyService _documentSircularyService;
    private readonly IDocumentTranslationService _documentTranslationService;
    
    private readonly string _connectionString;

    public ProformaInvoiceController(IConfiguration configuration,
        ICustomerService customerService, IProformaInvoiceService proformaInvoiceService, IDocumentAttestationService documentAttestationService, IDocumentCommitmentLetterService documentCommitmentLetterService, IDocumentConsentLetterService documentConsentLetterService, IDocumentInvitationService documentInvitationService, IDocumentPoaService documentPoaService, IDocumentSircularyService documentSircularyService, IDocumentTranslationService documentTranslationService, ISettingsService settingsService)
    {
        _customerService = customerService;
        _proformaInvoiceService = proformaInvoiceService;
        _documentAttestationService = documentAttestationService;
        _documentCommitmentLetterService = documentCommitmentLetterService;
        _documentConsentLetterService = documentConsentLetterService;
        _documentInvitationService = documentInvitationService;
        _documentPoaService = documentPoaService;
        _documentSircularyService = documentSircularyService;
        _documentTranslationService = documentTranslationService;
        _settingsService = settingsService;
        _connectionString = configuration.GetConnectionString("DefaultConnection");
    }
    
    public IActionResult ProformaInvoiceIndex(string str, bool first)
    {
        _proformaInvoiceService.Initialize();
        
        if(string.IsNullOrEmpty(str))
            return View(_proformaInvoiceService.AllProformaInvoices.ToArray());
            
        var proformaInvoiceModels = new List<ProformaInvoiceModel>();
        foreach (var proformaInvoiceModel in _proformaInvoiceService.AllProformaInvoices)
        {
            if (first && proformaInvoiceModel.ProformaInvoiceNo.ToString().Contains(str))
                proformaInvoiceModels.Add(proformaInvoiceModel);
            if(!first && proformaInvoiceModel.Customer.FullName.Contains(str))
                proformaInvoiceModels.Add(proformaInvoiceModel);
        }

        return View(proformaInvoiceModels.ToArray());
    }

    public IActionResult ChooseCustomerForProformaInvoicePage()
    {
        _customerService.Initialize();
        return View(_customerService.AllCustomers.ToArray());
    }
    
    public IActionResult ChooseServicePage(int id)
    {
        _documentAttestationService.Initialize();
        _documentCommitmentLetterService.Initialize();
        _documentConsentLetterService.Initialize();
        _documentInvitationService.Initialize();
        _documentPoaService.Initialize();
        _documentSircularyService.Initialize();
        _documentTranslationService.Initialize();
        
        var allDocumentsModel = new AllDocumentsModel();
        allDocumentsModel.DocumentAttestationModels = _documentAttestationService.AllDocumentAttestations
            .Where(x => x.CustomerId == id).ToArray();
        allDocumentsModel.DocumentCommitmentLetterModels = _documentCommitmentLetterService.AllDocumentCommitmentLetter
            .Where(x => x.CustomerId == id).ToArray();
        allDocumentsModel.DocumentConsentLetterModels = _documentConsentLetterService.AllDocumentConsentLetter
            .Where(x => x.CustomerId == id).ToArray();
        allDocumentsModel.DocumentInvitationModels = _documentInvitationService.AllDocumentInvitation
            .Where(x => x.CustomerId == id).ToArray();
        allDocumentsModel.DocumentPoaModels =
            _documentPoaService.AllDocumentPoa.Where(x => x.CustomerId == id).ToArray();
        allDocumentsModel.DocumentSircularyModels = _documentSircularyService.AllDocumentSirculary
            .Where(x => x.CustomerId == id).ToArray();
        allDocumentsModel.DocumentTranslationModels = _documentTranslationService.AllDocumentTranslations
            .Where(x => x.CustomerId == id).ToArray();
        allDocumentsModel.CustomerId = id;
        
        return View(allDocumentsModel);
    }
    
    public IActionResult CreateProformaInvoicePage(int customerId, List<int> selectedDocuments, List<string> documentTypes)
    {
        _proformaInvoiceService.Initialize();
        _settingsService.Initialize();
        _customerService.Initialize();
        var customer = _customerService.AllCustomers.FirstOrDefault(x => x.CustomerId == customerId);
        
        var items = new ProformaInvoiceItem[selectedDocuments.Count];
        for( var i = 0; i < selectedDocuments.Count; i++)
        {
            var document = new ProformaInvoiceItem
            {
                Description = documentTypes[i],
                UnitPrice = 0,
                Qty = 1,
                SubTotal = 0
            };
            
            document.Vat = documentTypes[i] switch
            {
                "DocumentAttestation" => _settingsService.AllSettings.First().AttestationTax,
                "DocumentCommitmentLetter" => _settingsService.AllSettings.First().CommitmentTax,
                "DocumentConsentLetter" => _settingsService.AllSettings.First().ConsentTax,
                "DocumentInvitation" => _settingsService.AllSettings.First().InvitationTax,
                "DocumentPoa" => _settingsService.AllSettings.First().PoaTax,
                "DocumentSirculary" => _settingsService.AllSettings.First().SircularyTax,
                "DocumentTranslation" => _settingsService.AllSettings.First().TranslationTax,
                _ => 0 // Default case, if documentTypes[i] doesn't match any case
            };
            document.VatString = document.Vat.ToString(CultureInfo.InvariantCulture);
            
            document.UnitPrice = documentTypes[i] switch
            {
                "DocumentAttestation" => _settingsService.AllSettings.First().AttestationPrice,
                "DocumentCommitmentLetter" => _settingsService.AllSettings.First().CommitmentPrice,
                "DocumentConsentLetter" => _settingsService.AllSettings.First().ConsentPrice,
                "DocumentInvitation" => _settingsService.AllSettings.First().InvitationPrice,
                "DocumentPoa" => _settingsService.AllSettings.First().PoaPrice,
                "DocumentSirculary" => _settingsService.AllSettings.First().SircularyPrice,
                "DocumentTranslation" => _settingsService.AllSettings.First().TranslationPrice,
                _ => 0 // Default case, if documentTypes[i] doesn't match any case
            };
            document.Qty = 1;
            document.UnitPriceString = document.UnitPrice.ToString(CultureInfo.InvariantCulture);
            items[i] = document;
        }
        
        var proformaInvoice = new ProformaInvoiceModel
        {
            Customer = customer,
            CustomerId = customer.CustomerId,
            Items =  items,
            InvoiceDate = DateTime.Today
        };
        return View(proformaInvoice);
    }

    public IActionResult EditProformaInvoicePage(int proformaInvoiceId)
    {
        _proformaInvoiceService.Initialize();
        var retrievedProformaInvoice =
            _proformaInvoiceService.AllProformaInvoices.Find(b => b.ProformaInvoiceId == proformaInvoiceId);
        return View(retrievedProformaInvoice);
    }


    [HttpPost]
    public IActionResult CreateProformaInvoice(ProformaInvoiceModel proformaInvoice)
    {
        ProformaInvoiceModel newProformaInvoice = new ProformaInvoiceModel
        {
            ProformaInvoiceNo = proformaInvoice.ProformaInvoiceNo,
            Items = proformaInvoice.Items,
            SubTotal = double.Parse(proformaInvoice.SubTotalString, CultureInfo.InvariantCulture),
            TotalTaxAmount = double.Parse(proformaInvoice.TotalTaxAmountString, CultureInfo.InvariantCulture),
            GrandTotal = double.Parse(proformaInvoice.GrandTotalString, CultureInfo.InvariantCulture),
            CreatedBy = proformaInvoice.CreatedBy,
            InvoiceDate = proformaInvoice.InvoiceDate
        };

        for (var i = 0; i < newProformaInvoice.Items.Length; i++)
        {
            newProformaInvoice.Descriptions += newProformaInvoice.Items[i].Description;
            newProformaInvoice.UnitPrices += newProformaInvoice.Items[i].UnitPriceString;
            newProformaInvoice.Qtys += newProformaInvoice.Items[i].Qty;
            newProformaInvoice.SubTotals += newProformaInvoice.Items[i].SubTotalString;
            newProformaInvoice.TaxAmounts += newProformaInvoice.Items[i].TaxAmountString;
            newProformaInvoice.Totals += newProformaInvoice.Items[i].TotalString;
            newProformaInvoice.Vats += newProformaInvoice.Items[i].VatString;
            
            if (i != newProformaInvoice.Items.Length - 1)
            {
                newProformaInvoice.Descriptions += "|";
                newProformaInvoice.UnitPrices += "|";
                newProformaInvoice.Qtys += "|";
                newProformaInvoice.SubTotals += "|";
                newProformaInvoice.TaxAmounts += "|";
                newProformaInvoice.Totals += "|";

Project 3/Project/Views/ProformaInvoice/ChooseCustomerForProformaInvoicePage.cshtml
@{
    ViewData["Title"] = "Customer Selection";
}

@model Project.Models.Customer[]


<div id="top-bar">
    <div id="selectedpanelitem">
        <h3>
            Customer Selection
        </h3>
    </div>
</div>

<br/><br/><br/>

<br/>

<table class="styled-table">
    <thead>
    <tr>
        <th>
            Type
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MotherName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MobileNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().WhatsAppNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TRNNumber)
        </th>

        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Satisfaction)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MotherName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MobileNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WhatsAppNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TRNNumber)
            </td>

            <td>
                <a class="tablebutton" href="@Url.Action("ChooseServicePage", "ProformaInvoice", new { id = item.CustomerId })">
                    <span class="tablebutton_text">Select</span>
                </a>
            </td>
        </tr>
    }
    </tbody>
</table>

Project 3/Project/Views/ProformaInvoice/ProformaInvoiceIndex.cshtml
@{
    ViewData["Title"] = "Proforma Invoice";
}

@model Project.Models.ProformaInvoiceModel[]

<!DOCTYPE html>

<div id="top-bar">
    <div id="panelitem">
        <h3>
            <a class="custom-link" href="@Url.Action("Index", "Home")"> Home</a>
        </h3>
    </div>
    <div id="selectedpanelitem">
        <h3>
            <a> Proforma Invoices</a>
        </h3>
    </div>
    <div id="panelitem">
        <h3>
            <a class="custom-link" href="@Url.Action("PendingIndex", "Pending")"> Pending</a>
        </h3>
    </div>
    <div id="panelitem">
        <h3>
            <a class="custom-link" href="@Url.Action("Index", "Accounting")"> Invoices</a>
        </h3>
    </div>

    <div id="panelitem">
        <h3>
            <a class="custom-link" href="@Url.Action("VoucherIndex", "Voucher")"> Vouchers</a>
        </h3>
    </div>
</div>

<br/><br/><br/><br/>

<div>
    <span style="display: inline-block;">
        <a href="@Url.Action("ChooseCustomerForProformaInvoicePage", "ProformaInvoice")" class="create-button">
            <span class="create-button__text">New</span>
            <span class="create-button__icon">
                <ion-icon name="add-circle-outline"></ion-icon>
            </span>
        </a>
        <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
    </span>

    <form asp-action="Search" method="post" style="display: inline-block;">
        <label for="searchCriteria">Search by:</label>
        <select id="searchCriteria" name="searchCriteria">
            <option value="ProformaInvoiceNumber">Proforma Invoice Number</option>
            <option value="Name">Name</option>
            <!-- Add other search options as needed -->
        </select>
        <input type="text" id="searchQuery" name="searchQuery"/>
        <button type="submit">Search</button>
    </form>
</div>


<table class="styled-table">
    <thead>
    <tr>
        <th>
            RefNo
        </th>
        <th>
            Name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Descriptions)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Items[0].Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().GrandTotal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Totals)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Items[0].Total)
        </th>

        <th></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProformaInvoiceNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descriptions)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Items[0].Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GrandTotal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Totals)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Items[0].Total)
            </td>

            <td>
                <a class="tablebutton" href="@Url.Action("ShowProformaInvoice", "ProformaInvoice", new { proformaInvoiceId = item.ProformaInvoiceId })">
                    <span class="tablebutton_text">Show</span>
                </a>
                <a class="tablebutton" href="@Url.Action("EditProformaInvoicePage", "ProformaInvoice", new { proformaInvoiceId = item.ProformaInvoiceId })">
                    <span class="tablebutton_text">Edit</span>
                </a>
                <a class="tablebutton" href="@Url.Action("DeleteProformaInvoice", "ProformaInvoice", new { proformaInvoiceId = item.ProformaInvoiceId })" onclick="return confirmDelete()">
                    <span class="tablebutton_text">Delete</span>
                </a>
            </td>
            <td>
                <a class="tablebutton" href="@Url.Action("RequestCreatePendingPage", "ProformaInvoice", new { proformaInvoiceId = item.ProformaInvoiceId })">
                    <span class="tablebutton_text">Create Pending</span>
                </a>
            </td>
            <td>
                <a class="tablebutton" href="@Url.Action("RequestCreateInvoicePage", "ProformaInvoice", new { proformaInvoiceId = item.ProformaInvoiceId })"  onclick="return createInvoice()">
                    <span class="tablebutton_text">Create Invoice</span>
                </a>
            </td>
            <td>
                <a class="tablebutton" href="@Url.Action("RequestCreateVoucherPage", "ProformaInvoice", new { proformaInvoiceId = item.ProformaInvoiceId })">
                    <span class="tablebutton_text">Create Voucher</span>
                </a>
            </td>
        </tr>
    }
    </tbody>
</table>

@section scripts {
    <script>
        function confirmDelete() {
                return confirm("Are you sure you want to delete this item?");
        }
        function createInvoice() {
                return confirm("Create Invoice?");
        }
    </script>
}